// import "./mathematics/task-1.js";
// import "./mathematics/task-2.js";
// import "./mathematics/task-3.js";
// import "./mathematics/task-4.js";
// import "./if-else/task-5.js";
// import "./logical-operators/task-2.js";
// import "./logical-operators/task-3.js";
// import "./logical-operators/task-5.js";
// import "./cycle/task-1.js"
// import "./cycle/task-2.js"
// import "./cycle/task-3.js"
// import "./cycle/task-4.js"
// import "./cycle/task-5.js";
// import "./cycle/task-6.js";
// import "./function/test-function.js"
// import "./function/task-4.js"
// import "./object/task-5.js"
// import "./this/task-2.js";
// import './array-methods/task-1.js';
// import './array-methods/task-2.js';
// import './array-methods/task-3.js';
// import './array-methods/task-4.js';
// import './array-methods/task-5.js';
// import './array-methods/task-6.js';
// import './array-methods/task-7.js';
// import './array-methods/task-8.js';
// import './array-methods/task-9.js';
// import './array-methods/task-10.js';
// import './array-methods/task-11.js';
// import './array-methods/task-12.js';
// import './array-methods/task-10.js';
// import './destructuring/task-2.js';


