// import "./mathematics/task-1.js";
// import "./mathematics/task-2.js";
// import "./mathematics/task-3.js";
// import "./mathematics/task-4.js";
// import "./if-else/task-5.js";
// import "./logical-operators/task-2.js";
// import "./logical-operators/task-3.js";
// import "./logical-operators/task-5.js";
// import "./cycle/task-1.js"
// import "./cycle/task-2.js"
// import "./cycle/task-3.js"
// import "./cycle/task-4.js"
// import "./cycle/task-5.js";
// import "./cycle/task-6.js";
// import "./function/test-function.js"
// import "./function/task-4.js"
// import "./object/task-5.js"
// import "./this/task-2.js";
// import "./this/task-3.js";
import "./numbers/task-6.js"